#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [[ -f "$DOKKU_ROOT/$APP/SLACK_URL" || -f "$DOKKU_ROOT/SLACK_URL" ]]; then
  URL=$(dokku url $APP)
  SLACK_URL=$(cat "$DOKKU_ROOT/$APP/SLACK_URL" 2> /dev/null || cat "$DOKKU_ROOT/SLACK_URL" 2> /dev/null)
  SLACK_CHANNEL=$(cat "$DOKKU_ROOT/$APP/SLACK_CHANNEL" 2> /dev/null || cat "$DOKKU_ROOT/SLACK_CHANNEL" 2> /dev/null || echo "#engineering")
  echo "-----> Notifying Slack ${SLACK_CHANNEL}..."
  SLACK_JSON="{ \
    \"channel\": \"$SLACK_CHANNEL\", \
    \"attachments\": [{ \
      \"text\": \"Deployed *$APP* \`$GIT_REV\` to *$HOSTNAME* via $URL\", \
      \"fallback\": \"Deployed $APP to $HOSTNAME via $URL\", \
      \"color\": \"good\", \
      \"mrkdwn_in\": [\"text\"] \
    }] \
  }"
  SLACK_RESULT=$(curl -s -d "payload=$SLACK_JSON" "${SLACK_URL}" -w "%{http_code}")
  echo "       ${SLACK_RESULT}"
fi
